default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rolf_sommer_rede_development

test:
  <<: *default
  database: rolf_sommer_rede_test

production:
  <<: *default
  database: rolf_sommer_rede_production
# **********************************************************
